<?php

namespace Database\Seeders;

use App\Models\Producto;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Producto::insert([
            ["id" => "1", "codigo_sku" => "AVE-16942269", "nombre" => "AVENA EN HOJUELAS", "descripcion" => "GLORIA - PESO NETO =>  400g", "unidad_medida" => "g", "precio_detal" => "1.05", "precio_embalaje" => "21.00", "stock_actual" => "100", "unidades_por_embalaje" => "20", "categoria_id" => "7", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "2", "codigo_sku" => "CAF-15964805", "nombre" => "CAFÉ TOSTADO Y MOLIDO GOURMET", "descripcion" => "CAFFAS - PESO NETO =>  200g", "unidad_medida" => "g", "precio_detal" => "1.65", "precio_embalaje" => "39.60", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "9", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "3", "codigo_sku" => "CAF-58402430", "nombre" => "CAFÉ TOSTADO Y MOLIDO GOURMET", "descripcion" => "CAFFAS - PESO NETO =>  100g", "unidad_medida" => "g", "precio_detal" => "0.82", "precio_embalaje" => "19.68", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "9", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "4", "codigo_sku" => "CAR-85173096", "nombre" => "CARAOTAS NEGRAS GRANOS", "descripcion" => "GLORIA - PESO NETO =>  500g", "unidad_medida" => "g", "precio_detal" => "1.30", "precio_embalaje" => "31.20", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "10", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "5", "codigo_sku" => "CAR-79231586", "nombre" => "CARAOTAS ROJAS GRANOS", "descripcion" => "GLORIA - PESO NETO =>  500g", "unidad_medida" => "g", "precio_detal" => "1.40", "precio_embalaje" => "33.60", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "10", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "6", "codigo_sku" => "CHA-57683798", "nombre" => "CHAMPIÑONES", "descripcion" => "AREL - PESO NETO =>  400g", "unidad_medida" => "g", "precio_detal" => "1.80", "precio_embalaje" => "43.20", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "8", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "7", "codigo_sku" => "GUI-37963145", "nombre" => "GUISANTES", "descripcion" => "AREL - PESO NETO =>  227g", "unidad_medida" => "g", "precio_detal" => "0.96", "precio_embalaje" => "23.04", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "8", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "8", "codigo_sku" => "GUI-40216125", "nombre" => "GUISANTES TIERNOS", "descripcion" => "AREL - PESO NETO =>  400g", "unidad_medida" => "g", "precio_detal" => "1.30", "precio_embalaje" => "31.20", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "8", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "9", "codigo_sku" => "HOJ-08263591", "nombre" => "HOJUELAS DE PAPAS FRITAS CON SAL", "descripcion" => "TERRA HISPANICA - PESO NETO =>  130g", "unidad_medida" => "g", "precio_detal" => "3.20", "precio_embalaje" => "64.00", "stock_actual" => "100", "unidades_por_embalaje" => "20", "categoria_id" => "5", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "10", "codigo_sku" => "HOJ-48360435", "nombre" => "HOJUELAS DE PAPAS FRITAS SABOR A JAMÓN", "descripcion" => "TERRA HISPANICA - PESO NETO =>  130g", "unidad_medida" => "g", "precio_detal" => "3.20", "precio_embalaje" => "64.00", "stock_actual" => "100", "unidades_por_embalaje" => "20", "categoria_id" => "5", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "11", "codigo_sku" => "HOJ-75208413", "nombre" => "HOJUELAS DE PAPAS FRITAS SABOR BARBACOA", "descripcion" => "TERRA HISPANICA - PESO NETO =>  130g", "unidad_medida" => "g", "precio_detal" => "3.20", "precio_embalaje" => "64.00", "stock_actual" => "100", "unidades_por_embalaje" => "20", "categoria_id" => "5", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "12", "codigo_sku" => "LEC-58910620", "nombre" => "LECHE CONDENSADA", "descripcion" => "AREL - PESO NETO =>  390g", "unidad_medida" => "g", "precio_detal" => "1.50", "precio_embalaje" => "72.00", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "2", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "13", "codigo_sku" => "LEC-83329070", "nombre" => "LECHE EN POLVO COMPLETA", "descripcion" => "GLORIA - PESO NETO =>  900g", "unidad_medida" => "g", "precio_detal" => "7.50", "precio_embalaje" => "90.00", "stock_actual" => "100", "unidades_por_embalaje" => "12", "categoria_id" => "2", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "14", "codigo_sku" => "LEN-67812439", "nombre" => "LENTEJAS GRANOS", "descripcion" => "GLORIA - PESO NETO =>  500g", "unidad_medida" => "g", "precio_detal" => "1.40", "precio_embalaje" => "33.60", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "10", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "15", "codigo_sku" => "LOM-54041767", "nombre" => "LOMO DE ATÚN AHUMADO", "descripcion" => "PÁFIA - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.63", "precio_embalaje" => "78.24", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "16", "codigo_sku" => "LOM-51795766", "nombre" => "LOMO DE ATÚN BLANCO FRESCO EN AGUA", "descripcion" => "AREL - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.46", "precio_embalaje" => "70.08", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "17", "codigo_sku" => "LOM-14563364", "nombre" => "LOMO DE ATÚN BLANCO FRESCO EN ACEITE", "descripcion" => "AREL - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.46", "precio_embalaje" => "70.08", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "18", "codigo_sku" => "LOM-11497805", "nombre" => "LOMO DE ATÚN BLANCO AHUMADO FRESCO EN ACEITE", "descripcion" => "AREL - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.65", "precio_embalaje" => "79.20", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "19", "codigo_sku" => "LOM-17142724", "nombre" => "LOMO DE ATÚN BLANCO EN ACEITE PICANTE", "descripcion" => "AREL - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.80", "precio_embalaje" => "86.40", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "20", "codigo_sku" => "LOM-28167435", "nombre" => "LOMO DE ATUN BLANCO FRESCO EN ACEITE DE OLIVA", "descripcion" => "AREL - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.92", "precio_embalaje" => "92.16", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "21", "codigo_sku" => "LOM-73643152", "nombre" => "LOMO DE ATÚN DESMENUZADO EN ACEITE VEGETAL LA RIVERA AZUL", "descripcion" => "AREL - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "0.94", "precio_embalaje" => "45.12", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "22", "codigo_sku" => "LOM-55948321", "nombre" => "LOMO DE ATUN DESMENUZADO EN AGUA LA RIVIERA AZUL", "descripcion" => "AREL - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "0.90", "precio_embalaje" => "43.20", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "23", "codigo_sku" => "LOM-43706502", "nombre" => "LOMO DE ATÚN EN ACEITE", "descripcion" => "PÁFIA - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.23", "precio_embalaje" => "59.04", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "24", "codigo_sku" => "LOM-06837242", "nombre" => "LOMO DE ATÚN EN ACEITE DE OLIVA", "descripcion" => "PÁFIA - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.83", "precio_embalaje" => "87.84", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "25", "codigo_sku" => "LOM-67513486", "nombre" => "LOMO DE ATÚN EN AGUA", "descripcion" => "PÁFIA - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.23", "precio_embalaje" => "59.04", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "26", "codigo_sku" => "LOM-50342517", "nombre" => "LOMO DE ATÚN EN AGUA SABOR A LIMÓN", "descripcion" => "PÁFIA - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.65", "precio_embalaje" => "79.19", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "27", "codigo_sku" => "LOM-27945172", "nombre" => "LOMO DE ATÚN ENSALADA CON VEGETALES", "descripcion" => "PÁFIA - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.63", "precio_embalaje" => "78.24", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "28", "codigo_sku" => "LOM-85134719", "nombre" => "LOMO DE ATÚN PICANTE", "descripcion" => "PÁFIA - PESO NETO =>  140g", "unidad_medida" => "g", "precio_detal" => "1.63", "precio_embalaje" => "78.24", "stock_actual" => "100", "unidades_por_embalaje" => "48", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "29", "codigo_sku" => "MAÍ-76203193", "nombre" => "MAÍZ DULCE EN GRANOS", "descripcion" => "AREL - PESO NETO =>  227g", "unidad_medida" => "g", "precio_detal" => "0.95", "precio_embalaje" => "22.80", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "6", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "30", "codigo_sku" => "MAÍ-31567414", "nombre" => "MAÍZ DULCE EN GRANOS", "descripcion" => "AREL - PESO NETO =>  400g", "unidad_medida" => "g", "precio_detal" => "1.50", "precio_embalaje" => "36.00", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "6", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "31", "codigo_sku" => "MEL-28314951", "nombre" => "MELOCOTONES EN ALMÍBAR DILUIDA", "descripcion" => "AREL - PESO NETO =>  425g", "unidad_medida" => "g", "precio_detal" => "1.70", "precio_embalaje" => "40.80", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "6", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "32", "codigo_sku" => "MEL-32067573", "nombre" => "MELOCOTONES EN ALMÍBAR DILUIDA", "descripcion" => "AREL - PESO NETO =>  820g", "unidad_medida" => "g", "precio_detal" => "3.40", "precio_embalaje" => "40.80", "stock_actual" => "100", "unidades_por_embalaje" => "12", "categoria_id" => "6", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "33", "codigo_sku" => "PAS-13721980", "nombre" => "PASTA DE TOMATE", "descripcion" => "AREL - PESO NETO =>  400g", "unidad_medida" => "g", "precio_detal" => "1.67", "precio_embalaje" => "40.08", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "6", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "34", "codigo_sku" => "SAR-04232565", "nombre" => "SARDINAS EN ACEITE", "descripcion" => "AREL - PESO NETO =>  170g", "unidad_medida" => "g", "precio_detal" => "0.64", "precio_embalaje" => "15.36", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "35", "codigo_sku" => "SAR-98641528", "nombre" => "SARDINAS EN SALSA", "descripcion" => "AREL - PESO NETO =>  170g", "unidad_medida" => "g", "precio_detal" => "0.60", "precio_embalaje" => "14.40", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "3", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "36", "codigo_sku" => "VEG-19620850", "nombre" => "VEGETALES MIXTOS", "descripcion" => "AREL - PESO NETO =>  227g", "unidad_medida" => "g", "precio_detal" => "1.80", "precio_embalaje" => "43.20", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "8", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"],
            ["id" => "37", "codigo_sku" => "VEG-26761718", "nombre" => "VEGETALES MIXTOS", "descripcion" => "AREL - PESO NETO =>  400g", "unidad_medida" => "g", "precio_detal" => "2.60", "precio_embalaje" => "62.40", "stock_actual" => "100", "unidades_por_embalaje" => "24", "categoria_id" => "8", "proveedor_id" => "1", "embalaje_id" => "2", "active" => "1"]
        ]);
    }
}
